<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'add' => 'Thêm',
    'add_product' => 'Thêm mặt hàng',
    'address' => 'Địa chỉ',
    'agency_info' => 'Thông tin đại lý',
    'agency_name' => 'Tên đại lý',
    'avatar' => 'Ảnh đại diện',
    'category' => 'Danh mục',
    'close' => 'Đóng',
    'common_info' => 'Thông tin chung',
    'description' => 'Mô tả',
    'edit' => 'Sửa',
    'edit_product' => 'Sửa mặt hàng',
    'email' => 'Email',
    'first_name' => 'Tên',
    'from_date' => 'Từ ngày',
    'no' => 'Không',
    'phone' => 'Điện thoại',
    'price' => 'Giá',
    'product' => 'Mặt hàng',
    'replace' => 'Thay đổi',
    'save' => 'Lưu',
    'sure_delete' => 'Chắc chắn xóa?',
    'to_date' => 'Đến ngày',
    'unit' => 'Đơn vị',
    'yes' => 'Có',
];
